'use strict';function q(e,a,b,c){e.A.mc(e.ab,a,b,c,void 0)}function D(e,a,b,c){e.A.ta?q(e,a,b,c):e.A.qf()._OnMessageFromDOM({type:"event",component:e.ab,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function F(e,a,b){e.A.C(e.ab,a,b)}function H(e,a){for(const [b,c]of a)F(e,b,c)}function I(e){e.Rb||(e.A.Ye(e.ge),e.Rb=!0)}window.oa=class{constructor(e,a){this.A=e;this.ab=a;this.Rb=!1;this.ge=()=>this.Ga()}gd(){}Ga(){}};function L(e){-1!==e.Ra&&(self.clearTimeout(e.Ra),e.Ra=-1)}
window.Pe=class{constructor(e,a){this.Oc=e;this.Gg=a;this.Ra=-1;this.Sb=-Infinity;this.he=()=>{this.Ra=-1;this.Sb=Date.now();this.gb=!0;this.Oc();this.gb=!1};this.Qd=this.gb=!1}c(){L(this);this.he=this.Oc=null}};"use strict";function M(e,a){const b=a.elementId,c=e.ld(b,a);e.Z.set(b,c);a.isVisible||(c.style.display="none");a=e.wc(c);a.addEventListener("focus",()=>{N(e,"elem-focused",b)});a.addEventListener("blur",()=>{N(e,"elem-blurred",b)});e.Mb&&document.body.appendChild(c)}
function O(e,a){F(e,"get-element",b=>{const c=e.Z.get(b.elementId);return a(c,b)})}function N(e,a,b){var c;c||(c={});c.elementId=b;q(e,a,c)}
window.Ce=class extends self.oa{constructor(e,a){super(e,a);this.Z=new Map;this.Mb=!0;H(this,[["create",b=>M(this,b)],["destroy",b=>{{b=b.elementId;const c=this.Z.get(b);this.Mb&&c.parentElement.removeChild(c);this.Z.delete(b)}}],["set-visible",b=>{this.Mb&&(this.Z.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Mb){var c=this.Z.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;
null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.Z.get(b.elementId);this.sc(c,b)}}],["focus",b=>this.Ic(b)],["set-css-style",b=>{this.Z.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Z.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Z.get(b.elementId).removeAttribute(b.name)}]]);O(this,b=>b)}ld(){throw Error("required override");}sc(){throw Error("required override");}wc(e){return e}Ic(e){const a=this.wc(this.Z.get(e.elementId));
e.focus?a.focus():a.blur()}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(h){const d=document.createElement("script");d.async=!1;d.type="module";return h.Ug?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;d.textContent=h.Xg+`\n\nself["${l}"]();`;document.head.appendChild(d)}):new Promise((k,l)=>{d.onload=k;d.onerror=l;d.src=h;document.head.appendChild(d)})}let c=!1,g=!1;function m(){if(!c){try{new Worker("blob://",{get type(){g=!0}})}catch(h){}c=!0}return g}let p=
new Audio;const t={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function x(h){h=await z(h);return(new TextDecoder("utf-8")).decode(h)}function z(h){return new Promise((d,
k)=>{const l=new FileReader;l.onload=n=>d(n.target.result);l.onerror=n=>k(n);l.readAsArrayBuffer(h)})}const w=[];let y=0;window.RealFile=window.File;const C=[],G=new Map,A=new Map;let J=0;const E=[];self.runOnStartup=function(h){if("function"!==typeof h)throw Error("runOnStartup called without a function");E.push(h)};const K=new Set(["cordova","playable-ad","instant-games"]);let f=!1;window.X=class h{constructor(d){this.ta=d.Zg;this.ra=null;this.F="";this.$b=d.Wg;this.ub={};this.Ka=this.tb=null;this.Pb=
[];this.ib=this.K=this.Pa=null;this.Oa=-1;this.Pg=()=>this.Of();this.Na=[];this.u=d.ie;!this.ta||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.ta=!1);K.has(this.u)&&this.ta&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is currently disabled in WebViews. Reverting to DOM mode."),this.ta=!1);this.Ub=this.ia=null;"html5"!==this.u&&"playable-ad"!==this.u||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.C("runtime","cordova-fetch-local-file",k=>this.xf(k));this.C("runtime","create-job-worker",()=>this.yf());"cordova"===this.u?document.addEventListener("deviceready",()=>this.Dd(d)):this.Dd(d)}c(){this.tc();this.ra&&(this.ra=this.ra.onmessage=null);this.tb&&(this.tb.terminate(),this.tb=null);this.Ka&&(this.Ka.c(),this.Ka=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}qd(){return e&&"cordova"===this.u}lc(){return e&&K.has(this.u)||navigator.standalone}async Dd(d){"macos-wkwebview"===
this.u&&this.Mc({type:"ready"});if("playable-ad"===this.u){this.ia=self.c3_base64files;this.Ub={};await this.cf();for(let l=0,n=d.Sa.length;l<n;++l){var k=d.Sa[l].toLowerCase();this.Ub.hasOwnProperty(k)?d.Sa[l]={Ug:!0,Xg:this.Ub[k]}:this.ia.hasOwnProperty(k)&&(d.Sa[l]=URL.createObjectURL(this.ia[k]))}}d.Qg?this.F=d.Qg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));d.ah&&(this.ub=d.ah);k=new MessageChannel;this.ra=
k.port1;this.ra.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Kf(l));this.ib=new self.Le(this);await P(this.ib);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ta?await this.sf(d,k.port2):await this.rf(d,k.port2)}xc(d){d=this.ub.hasOwnProperty(d)?this.ub[d]:d.endsWith("/workermain.js")&&this.ub.hasOwnProperty("workermain.js")?
this.ub["workermain.js"]:"playable-ad"===this.u&&this.ia.hasOwnProperty(d.toLowerCase())?this.ia[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async ec(d,k,l){if(d.startsWith("blob:"))return new Worker(d,l);if(this.qd()&&"file:"===location.protocol)return d=await this.vb(this.$b+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),l);d=new URL(d,k);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");
d=await d.blob();return new Worker(URL.createObjectURL(d),l)}return new Worker(d,l)}ya(){return Math.max(window.innerWidth,1)}xa(){return Math.max(window.innerHeight,1)}zd(d){var k=this.ib;return{baseUrl:this.F,windowInnerWidth:this.ya(),windowInnerHeight:this.xa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:h.Va(),projectData:d.hh,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.fh||"",exportType:d.ie,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.gh,jobScheduler:{inputPort:k.Uc,outputPort:k.ad,maxNumWorkers:k.Mg},supportedAudioFormats:t,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$b+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.$b+"opus.wasm.wasm",isiOSCordova:this.qd(),isiOSWebView:this.lc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async sf(d,k){var l=this.xc(d.$g);this.tb=await this.ec(l,this.F,
{type:"module",name:"Runtime"});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;this.tb.postMessage(Object.assign(this.zd(d),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:d.fd||[],engineScripts:d.Sa,projectScripts:d.ke,mainProjectScript:d.je,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...Q(this.ib)]);this.Pb=C.map(n=>new n(this));this.yd();
self.c3_callFunction=(n,u)=>this.Pa.tf(n,u);"preview"===this.u&&(self.goToLastErrorScript=()=>this.mc("runtime","go-to-last-error-script"))}async rf(d,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Pb=C.map(r=>new r(this));this.yd();var l=d.Sa.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(d.fd)&&l.unshift(...d.fd);l=await Promise.all(l.map(r=>this.Bc(r)));await Promise.all(l.map(r=>b(r)));
l=self.C3_ProjectScriptsStatus;const n=d.je,u=d.ke;for(let [r,v]of u)if(v||(v=r),r===n)try{v=await this.Bc(v),await b(v),"preview"!==this.u||l[r]||this.Ld(r,"main script did not run to completion")}catch(B){this.Ld(r,B)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))v=await this.Bc(v),await b(v);"preview"===this.u&&"object"!==typeof self.bh.dh?(this.Hb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this.zd(d),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:E}),this.Fd(),this.Ka=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.Ka,d))}Ld(d,k){this.Hb();console.error(`[Preview] Failed to load project main script (${d}): `,k);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Fd(){this.Hb()}Hb(){const d=
window.Rg;d&&(d.parentElement.removeChild(d),window.Rg=null)}async yf(){const d=await R(this.ib);return{outputPort:d,transferables:[d]}}qf(){if(this.ta)throw Error("not available in worker mode");return this.Ka}mc(d,k,l,n,u){this.ra.postMessage({type:"event",component:d,handler:k,dispatchOpts:n||null,data:l,responseId:null},u)}rd(d,k,l,n,u){const r=J++,v=new Promise((B,V)=>{A.set(r,{resolve:B,reject:V})});this.ra.postMessage({type:"event",component:d,handler:k,dispatchOpts:n||null,data:l,responseId:r},
u);return v}["_OnMessageFromRuntime"](d){const k=d.type;if("event"===k)return this.Df(d);if("result"===k)this.Sf(d);else if("runtime-ready"===k)this.Tf();else if("alert-error"===k)this.Hb(),alert(d.message);else if("creating-runtime"===k)this.Fd();else throw Error(`unknown message '${k}'`);}Df(d){const k=d.component,l=d.handler,n=d.data,u=d.responseId;if(d=G.get(k))if(d=d.get(l)){var r=null;try{r=d(n)}catch(v){console.error(`Exception in '${k}' handler '${l}':`,v);null!==u&&this.Gb(u,!1,""+v);return}if(null===
u)return r;r&&r.then?r.then(v=>this.Gb(u,!0,v)).catch(v=>{console.error(`Rejection from '${k}' handler '${l}':`,v);this.Gb(u,!1,""+v)}):this.Gb(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Gb(d,k,l){let n;l&&l.transferables&&(n=l.transferables);this.ra.postMessage({type:"result",responseId:d,isOk:k,result:l},n)}Sf(d){const k=d.responseId,l=d.isOk;d=d.result;const n=A.get(k);l?n.resolve(d):n.reject(d);A.delete(k)}C(d,
k,l){let n=G.get(d);n||(n=new Map,G.set(d,n));if(n.has(k))throw Error(`[DOM] Component '${d}' already has handler '${k}'`);n.set(k,l)}static na(d){if(C.includes(d))throw Error("DOM handler already added");C.push(d)}yd(){for(const d of this.Pb)if("runtime"===d.ab){this.Pa=d;return}throw Error("cannot find runtime DOM handler");}Kf(d){this.mc("debugger","message",d)}Tf(){for(const d of this.Pb)d.gd()}static Va(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
f)}static Ib(d){f=!!d}Ye(d){this.Na.push(d);this.Lc()}gg(d){d=this.Na.indexOf(d);if(-1===d)throw Error("invalid callback");this.Na.splice(d,1);this.Na.length||this.tc()}Lc(){-1===this.Oa&&this.Na.length&&(this.Oa=requestAnimationFrame(this.Pg))}tc(){-1!==this.Oa&&(cancelAnimationFrame(this.Oa),this.Oa=-1)}Of(){this.Oa=-1;for(const d of this.Na)d();this.Lc()}wa(d){this.Pa.wa(d)}Fa(d){this.Pa.Fa(d)}Kc(){this.Pa.Kc()}Bb(d){this.Pa.Bb(d)}Ke(){return!!t["audio/webm; codecs=opus"]}async Eg(d){d=await this.rd("runtime",
"opus-decode",{arrayBuffer:d},null,[d]);return new Float32Array(d)}Je(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}pd(d){return!this.Je(d)}async Bc(d){return"cordova"===this.u&&(d.startsWith("file:")||"file:"===location.protocol&&this.pd(d))?(d.startsWith(this.F)&&(d=d.substr(this.F.length)),d=await this.vb(d),URL.createObjectURL(new Blob([d],{type:"application/javascript"}))):d}async xf(d){const k=d.filename;switch(d.as){case "text":return await this.Be(k);
case "buffer":return await this.vb(k);default:throw Error("unsupported type");}}kd(d){const k=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,n)},n)})}async Be(d){d=await this.kd(d);return await x(d)}uc(){if(w.length&&!(8<=y)){y++;var d=w.shift();this.df(d.filename,d.Yg,d.Tg)}}vb(d){return new Promise((k,l)=>{w.push({filename:d,Yg:n=>{y--;this.uc();k(n)},Tg:n=>{y--;this.uc();l(n)}});this.uc()})}async df(d,k,
l){try{const n=await this.kd(d),u=await z(n);k(u)}catch(n){l(n)}}Mc(d){if("windows-webview2"===this.u)window.chrome.webview.postMessage(JSON.stringify(d));else if("macos-wkwebview"===this.u)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(d));else throw Error("cannot send wrapper message");}async cf(){const d=[];for(const [k,l]of Object.entries(this.ia))d.push(this.bf(k,l));await Promise.all(d)}async bf(d,k){if("object"===typeof k)this.ia[d]=new Blob([k.str],{type:k.type}),this.Ub[d]=
k.str;else{let l=await this.nf(k);l||(l=this.hf(k));this.ia[d]=l}}async nf(d){try{return await (await fetch(d)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}hf(d){d=this.ag(d);return this.af(d.data,d.Vg)}ag(d){var k=d.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=d.substring(k+1);
k=d.substring(5,k).split(";");d=k[0]||"";const n=k[2];l="base64"===k[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Vg:d,data:l}}af(d,k){var l=d.length;let n=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,n),v,B;for(B=v=0;v<n;++v)r[v]=d.charCodeAt(B++)|d.charCodeAt(B++)<<8|d.charCodeAt(B++)<<16|d.charCodeAt(B++)<<24;for(l&=3;l--;)u[B]=d.charCodeAt(B),++B;return new Blob([u],{type:k})}}}"use strict";
{const e=self.X;function a(f){return f.sourceCapabilities&&f.sourceCapabilities.firesTouchEvents||f.originalEvent&&f.originalEvent.sourceCapabilities&&f.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(f){return new Promise((h,d)=>{const k=document.createElement("link");k.onload=()=>h(k);k.onerror=l=>d(l);k.rel=
"stylesheet";k.href=f;document.head.appendChild(k)})}function t(f){return new Promise((h,d)=>{const k=new Image;k.onload=()=>h(k);k.onerror=l=>d(l);k.src=f})}async function x(f){f=URL.createObjectURL(f);try{return await t(f)}finally{URL.revokeObjectURL(f)}}function z(f){return new Promise((h,d)=>{let k=new FileReader;k.onload=l=>h(l.target.result);k.onerror=l=>d(l);k.readAsText(f)})}async function w(f,h,d){if(!/firefox/i.test(navigator.userAgent))return await x(f);var k=await z(f);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),u=l.getAttribute("height");if(!n.includes("%")&&!u.includes("%"))return await x(f)}l.setAttribute("width",h+"px");l.setAttribute("height",d+"px");k=(new XMLSerializer).serializeToString(k);f=new Blob([k],{type:"image/svg+xml"});return await x(f)}function y(f){do{if(f.parentNode&&f.hasAttribute("contenteditable"))return!0;f=f.parentNode}while(f);return!1}const C=new Set(["input",
"textarea","datalist","select"]),G=new Set(["canvas","body","html"]);function A(f){G.has(f.target.tagName.toLowerCase())&&f.preventDefault()}function J(f){(f.metaKey||f.ctrlKey)&&f.preventDefault()}self.C3_GetSvgImageSize=async function(f){f=await x(f);if(0<f.width&&0<f.height)return[f.width,f.height];{f.style.position="absolute";f.style.left="0px";f.style.top="0px";f.style.visibility="hidden";document.body.appendChild(f);const h=f.getBoundingClientRect();document.body.removeChild(f);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(f,h,d,k,l){f=await w(f,h,d);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(f,0,0,h,d);return n};let E=!1;document.addEventListener("pause",()=>E=!0);document.addEventListener("resume",()=>E=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(f){return!1}}e.na(class extends self.oa{constructor(f){super(f,"runtime");this.Vd=!0;this.Qa=-1;this.cd="any";this.Md=this.Nd=!1;this.Xc=
this.qb=this.Aa=null;f.C("canvas","update-size",k=>this.Yf(k));f.C("runtime","invoke-download",k=>this.If(k));f.C("runtime","raster-svg-image",k=>this.Pf(k));f.C("runtime","get-svg-image-size",k=>this.Ff(k));f.C("runtime","set-target-orientation",k=>this.Uf(k));f.C("runtime","register-sw",()=>this.Rf());f.C("runtime","post-to-debugger",k=>this.Hd(k));f.C("runtime","go-to-script",k=>this.Hd(k));f.C("runtime","before-start-ticking",()=>this.wf());f.C("runtime","debug-highlight",k=>this.zf(k));f.C("runtime",
"enable-device-orientation",()=>this.$e());f.C("runtime","enable-device-motion",()=>this.Ze());f.C("runtime","add-stylesheet",k=>this.vf(k));f.C("runtime","alert",k=>this.Cc(k));f.C("runtime","hide-cordova-splash",()=>this.Gf());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;h.has(l.tagName.toLowerCase())||y(l)||k.preventDefault()});const d=f.K;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);d.addEventListener("selectstart",
A);d.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),d.addEventListener("pointerdown",A)):d.addEventListener("touchstart",A);this.nb=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",J,{passive:!1});window.addEventListener("wheel",J,{passive:!1});window.addEventListener("resize",()=>this.Zf());window.addEventListener("fullscreenchange",
()=>this.Xa());window.addEventListener("webkitfullscreenchange",()=>this.Xa());window.addEventListener("mozfullscreenchange",()=>this.Xa());window.addEventListener("fullscreenerror",k=>this.Ec(k));window.addEventListener("webkitfullscreenerror",k=>this.Ec(k));window.addEventListener("mozfullscreenerror",k=>this.Ec(k));f.lc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var k=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));
k="textarea"===k?!0:"input"===k?l.has(n.type.toLowerCase()||"text"):y(n)}else k=!1}k||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=k=>this.$f(k);this.La=new Set;this.Vb=new WeakSet;this.qa=!1}wf(){"cordova"===this.A.u?(document.addEventListener("pause",()=>this.Jc(!0)),document.addEventListener("resume",()=>this.Jc(!1))):document.addEventListener("visibilitychange",()=>this.Jc(document.hidden));return{isSuspended:!(!document.hidden&&!E)}}gd(){window.addEventListener("focus",()=>
this.Za("window-focus"));window.addEventListener("blur",()=>{this.Za("window-blur",{parentHasFocus:K()});this.nb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||y(h))&&this.Za("keyboard-blur")});window.addEventListener("keydown",h=>this.Gd("keydown",h));window.addEventListener("keyup",h=>this.Gd("keyup",h));window.addEventListener("dblclick",h=>this.Gc("dblclick",h,c));window.addEventListener("wheel",h=>this.Mf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.yc(h);this.Ya("pointerdown",h)}),this.A.ta&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.qb=new self.Pe(()=>this.lf(),5),this.qb.Qd=!0,window.addEventListener("pointerrawupdate",h=>this.Nf(h))):window.addEventListener("pointermove",h=>this.Ya("pointermove",h)),window.addEventListener("pointerup",h=>this.Ya("pointerup",h)),window.addEventListener("pointercancel",h=>this.Ya("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.yc(h);this.Hc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Hc("pointermove",h)),window.addEventListener("mouseup",h=>this.Hc("pointerup",h)),window.addEventListener("touchstart",h=>{this.yc(h);this.Fb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Fb("pointermove",h)),window.addEventListener("touchend",h=>this.Fb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Fb("pointercancel",h)));const f=()=>this.Kc();window.addEventListener("pointerup",f,!0);window.addEventListener("touchend",
f,!0);window.addEventListener("click",f,!0);window.addEventListener("keydown",f,!0);window.addEventListener("gamepadconnected",f,!0)}Za(f,h){q(this,f,h||null,m)}ya(){return this.A.ya()}xa(){return this.A.xa()}Zf(){const f=this.ya(),h=this.xa();this.Za("window-resize",{innerWidth:f,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.Va()});this.A.lc()&&(-1!==this.Qa&&clearTimeout(this.Qa),this.Id(f,h,0))}hg(f,h,d){-1!==this.Qa&&clearTimeout(this.Qa);this.Qa=setTimeout(()=>this.Id(f,
h,d),48)}Id(f,h,d){const k=this.ya(),l=this.xa();this.Qa=-1;k!=f||l!=h?this.Za("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.Va()}):10>d&&this.hg(k,l,d+1)}Uf(f){this.cd=f.targetOrientation}Ag(){const f=this.cd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(f):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(f):screen.mozLockOrientation?h=screen.mozLockOrientation(f):screen.msLockOrientation&&(h=screen.msLockOrientation(f));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Xa(){const f=e.Va();f&&"any"!==this.cd&&this.Ag();q(this,"fullscreenchange",{isFullscreen:f,innerWidth:this.ya(),innerHeight:this.xa()})}Ec(f){console.warn("[Construct 3] Fullscreen request failed: ",f);q(this,"fullscreenerror",
{isFullscreen:e.Va(),innerWidth:this.ya(),innerHeight:this.xa()})}Jc(f){f?this.A.tc():this.A.Lc();q(this,"visibilitychange",{hidden:f})}Gd(f,h){"Backspace"===h.key&&A(h);const d=b.get(h.code)||h.code;D(this,f,{code:d,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},c)}Mf(f){q(this,"wheel",{clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,deltaX:f.deltaX,deltaY:f.deltaY,deltaZ:f.deltaZ,deltaMode:f.deltaMode,
timeStamp:f.timeStamp},c)}Gc(f,h,d){a(h)||D(this,f,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},d)}Hc(f,h){if(!a(h)){var d=this.nb;"pointerdown"===f&&0!==d?f="pointermove":"pointerup"===f&&0!==h.buttons&&(f="pointermove");D(this,f,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},c);this.nb=h.buttons;this.Gc(h.type,h,g)}}Ya(f,h){if(this.qb&&"pointermove"!==f){var d=this.qb;d.gb||(L(d),d.Sb=Date.now())}d=0;"mouse"===h.pointerType&&(d=this.nb);D(this,f,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},c);"mouse"===h.pointerType&&(d="mousemove","pointerdown"===f?d="mousedown":"pointerup"===f&&(d="mouseup"),this.Gc(d,h,g),this.nb=h.buttons)}Nf(f){this.Xc=f;f=this.qb;if(-1===f.Ra){var h=Date.now(),d=h-f.Sb,k=f.Gg;d>=k&&f.Qd?(f.Sb=h,f.gb=!0,f.Oc(),f.gb=!1):f.Ra=self.setTimeout(f.he,Math.max(k-d,4))}}lf(){this.Ya("pointermove",this.Xc);this.Xc=null}Fb(f,h){for(let d=0,k=h.changedTouches.length;d<k;++d){const l=h.changedTouches[d];D(this,f,{pointerId:l.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:h.timeStamp},c)}}yc(f){window!==window.top&&window.focus();this.Ed(f.target)&&document.activeElement&&!this.Ed(document.activeElement)&&document.activeElement.blur()}Ed(f){return!f||f===document||
f===window||f===document.body||"canvas"===f.tagName.toLowerCase()}$e(){this.Nd||(this.Nd=!0,window.addEventListener("deviceorientation",f=>this.Bf(f)),window.addEventListener("deviceorientationabsolute",f=>this.Cf(f)))}Ze(){this.Md||(this.Md=!0,window.addEventListener("devicemotion",f=>this.Af(f)))}Bf(f){q(this,"deviceorientation",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp,webkitCompassHeading:f.webkitCompassHeading,webkitCompassAccuracy:f.webkitCompassAccuracy},
c)}Cf(f){q(this,"deviceorientationabsolute",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp},c)}Af(f){let h=null;var d=f.acceleration;d&&(h={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var k=f.accelerationIncludingGravity;k&&(d={x:k.x||0,y:k.y||0,z:k.z||0});k=null;const l=f.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});q(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:d,rotationRate:k,interval:f.interval,timeStamp:f.timeStamp},
c)}Yf(f){const h=this.A.K;h.style.width=f.styleWidth+"px";h.style.height=f.styleHeight+"px";h.style.marginLeft=f.marginLeft+"px";h.style.marginTop=f.marginTop+"px";this.Vd&&(h.style.display="",this.Vd=!1)}If(f){const h=f.url;f=f.filename;const d=document.createElement("a"),k=document.body;d.textContent=f;d.href=h;d.download=f;k.appendChild(d);d.click();k.removeChild(d)}async Pf(f){var h=f.imageBitmapOpts;f=await self.C3_RasterSvgImageBlob(f.blob,f.imageWidth,f.imageHeight,f.surfaceWidth,f.surfaceHeight);
h=h?await createImageBitmap(f,h):await createImageBitmap(f);return{imageBitmap:h,transferables:[h]}}async Ff(f){return await self.C3_GetSvgImageSize(f.blob)}async vf(f){await p(f.url)}Kc(){var f=[...this.La];this.La.clear();if(!this.qa)for(const h of f)(f=h.play())&&f.catch(()=>{this.Vb.has(h)||this.La.add(h)})}wa(f){if("function"!==typeof f.play)throw Error("missing play function");this.Vb.delete(f);let h;try{h=f.play()}catch(d){this.La.add(f);return}h&&h.catch(()=>{this.Vb.has(f)||this.La.add(f)})}Fa(f){this.La.delete(f);
this.Vb.add(f)}Bb(f){this.qa=!!f}Gf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}zf(f){if(f.show){this.Aa||(this.Aa=document.createElement("div"),this.Aa.id="inspectOutline",document.body.appendChild(this.Aa));var h=this.Aa;h.style.display="";h.style.left=f.left-1+"px";h.style.top=f.top-1+"px";h.style.width=f.width+2+"px";h.style.height=f.height+2+"px";h.textContent=f.name}else this.Aa&&(this.Aa.style.display="none")}Rf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Hd(f){window.c3_postToMessagePort&&
(f.from="runtime",window.c3_postToMessagePort(f))}tf(f,h){return this.A.rd(this.ab,"js-invoke-function",{name:f,params:h},void 0,void 0)}Cc(f){alert(f.message)}$f(f){"entered-fullscreen"===f?(e.Ib(!0),this.Xa()):"exited-fullscreen"===f?(e.Ib(!1),this.Xa()):console.warn("Unknown wrapper message: ",f)}})}"use strict";
async function P(e){if(e.Fg)throw Error("already initialised");e.Fg=!0;var a=e.Zb.xc("dispatchworker.js");e.Qc=await e.Zb.ec(a,e.F,{name:"DispatchWorker"});a=new MessageChannel;e.Uc=a.port1;e.Qc.postMessage({type:"_init","in-port":a.port2},[a.port2]);e.ad=await R(e)}function Q(e){return[e.Uc,e.ad]}
async function R(e){const a=e.Wd.length;var b=e.Zb.xc("jobworker.js");b=await e.Zb.ec(b,e.F,{name:"JobWorker"+a});const c=new MessageChannel,g=new MessageChannel;e.Qc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":g.port2},[c.port2,g.port2]);e.Wd.push(b);return g.port1}
self.Le=class{constructor(e){this.Zb=e;this.F=e.F;this.F="preview"===e.u?this.F+"c3/workers/":this.F+e.$b;this.Mg=Math.min(navigator.hardwareConcurrency||2,16);this.Qc=null;this.Wd=[];this.ad=this.Uc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.X({Zg:!1,$g:"workermain.js",Sa:["scripts/c3runtime.js"],ke:[],je:"",Wg:"scripts/",fd:[],ie:"cordova"}));"use strict";
async function S(e,a){a=a.type;let b=!0;0===a?b=await T():1===a&&(b=await U());q(e,"permission-result",{type:a,result:b})}async function T(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request orientation permission: ",e),!1}}
async function U(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request motion permission: ",e),!1}}self.X.na(class extends self.oa{constructor(e){super(e,"touch");F(this,"request-permission",a=>S(this,a))}});"use strict";
{function e(a){a.stopPropagation()}self.X.na(class extends self.Ce{constructor(a){super(a,"button")}ld(a,b){const c=document.createElement("input");var g=c;b.isCheckbox?(c.type="checkbox",g=document.createElement("label"),g.appendChild(c),g.appendChild(document.createTextNode("")),g.style.fontFamily="sans-serif",g.style.userSelect="none",g.style.webkitUserSelect="none",g.style.display="inline-block",g.style.color="black"):c.type="button";g.style.position="absolute";g.addEventListener("touchstart",
e);g.addEventListener("touchmove",e);g.addEventListener("touchend",e);g.addEventListener("mousedown",e);g.addEventListener("mouseup",e);g.addEventListener("keydown",e);g.addEventListener("keyup",e);c.addEventListener("click",()=>{var m={isChecked:c.checked};m.elementId=a;D(this,"click",m)});b.id&&(c.id=b.id);this.sc(g,b);return g}Ad(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}wc(a){return this.Ad(a)}sc(a,b){const c=this.Ad(a);c.checked=b.isChecked;c.disabled=!b.isEnabled;a.title=b.title;
a===c?c.value=b.text:a.lastChild.textContent=b.text}})}"use strict";function aa(e){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>q(e,"sw-message",a.data))}
function ba(e){e=e.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(e):screen.webkitLockOrientation?a=screen.webkitLockOrientation(e):screen.mozLockOrientation?a=screen.mozLockOrientation(e):screen.msLockOrientation&&(a=screen.msLockOrientation(e));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.X.na(class extends self.oa{constructor(e){super(e,"browser");this.u="";H(this,[["get-initial-state",a=>this.Fc(a)],["ready-for-sw-messages",()=>aa(this)],["alert",a=>this.Cc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ic(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ba(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===
b){b=a.url;var c=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.eh||(2===c?window.top.location=b:1===c?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,c=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,c))}],["request-fullscreen",a=>{if("windows-webview2"===this.u||"macos-wkwebview"===this.u)self.X.Ib(!0),this.A.Mc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):
a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.u||"macos-wkwebview"===this.u?(self.X.Ib(!1),this.A.Mc({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&
document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{q(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{q(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{q(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{q(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",
a=>{a.handled=!0;q(this,"backbutton")})}Fc(e){this.u=e.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}Cc(e){alert(e.message)}Ic(e){e=e.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():
null;e?a.focus():a.blur()}else e?window.focus():window.blur()}});"use strict";async function ca(e){if(!e.Ca)try{e.Ca=await navigator.wakeLock.request("screen"),e.Ca.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");e.Ca=null;q(e,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),q(e,"wake-lock-acquired")}catch(a){console.warn("[Construct 3] Failed to acquire screen wake lock: ",a),q(e,"wake-lock-error")}}
function W(){var e=document.body;const a=e.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");e=getComputedStyle(e);e=[e.getPropertyValue("--temp-sai-top"),e.getPropertyValue("--temp-sai-right"),e.getPropertyValue("--temp-sai-bottom"),e.getPropertyValue("--temp-sai-left")].map(b=>{b=parseInt(b,10);
return isFinite(b)?b:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return e}
self.X.na(class extends self.oa{constructor(e){super(e,"platform-info");H(this,[["get-initial-state",()=>this.Fc()],["request-wake-lock",()=>ca(this)],["release-wake-lock",()=>{this.Ca&&(this.Ca.release(),this.Ca=null)}]]);window.addEventListener("resize",()=>{q(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:W()})});this.Ca=null}Fc(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:W(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";
{function e(){const a=self.RealFile||self.File;return"function"===typeof navigator.canShare&&navigator.canShare({files:[new a(["test file"],"test.txt",{})]})}self.X.na(class extends self.oa{constructor(a){super(a,"share");a=!!this.Cd();this.Jg=(this.Lg="function"===typeof navigator.share)||a;this.Hg=(this.Kg=e())||a;H(this,[["init",()=>this.Hf()],["share",b=>this.Vf(b)],["request-rate",b=>this.Qf(b)],["request-store",b=>this.Wf(b)]])}Hf(){return{isSupported:this.Jg,isFilesSupported:this.Hg}}Cd(){return window.plugins&&
window.plugins.socialsharing}Bd(){return window.cordova&&window.cordova.plugins&&window.cordova.plugins.RateApp}async Vf(a){var b=a.text;const c=a.title,g=a.url;a=a.files.slice(0);const m=0<a.length,p=this.Cd();if(p){const x={};b&&(x.message=b);c&&(x.subject=c);g&&(x.url=g);if(m){b=0;for(var t of a)b+=t.size;try{const z=await this.ef(Math.floor(1.25*b));x.files=await Promise.all(a.map(w=>this.ff(w,z)))}catch(z){console.log("[Share plugin] Share failed: ",z);q(this,"share-failed");return}}p.shareWithOptions(x,
()=>{q(this,"share-completed")},z=>{console.log("[Share plugin] Share failed: ",z);q(this,"share-failed")})}else{t={};b&&(t.text=b);c&&(t.title=c);g&&(t.url=g);m&&(t.files=a);try{await navigator.share(t),q(this,"share-completed")}catch(x){console.log("[Share plugin] Share failed: ",x),q(this,"share-failed")}}}Qf(a){const b=a.body,c=a.confirm,g=a.cancel;a=a.appID;const m=this.Bd();m&&m.Rate(b,c,g,a)}Wf(a){a=a.appID;const b=this.Bd();b&&b.Store(a)}ef(a){return new Promise((b,c)=>{window.requestFileSystem(window.TEMPORARY,
a,g=>b(g.root),c)})}ff(a,b){return new Promise((c,g)=>{b.getFile(a.name,{create:!0,exclusive:!1},m=>{const p=m.toURL();m.createWriter(t=>{t.onwriteend=()=>c(p);t.onerror=g;t.write(a)})},g)})}})}"use strict";self.X.na(class extends self.oa{constructor(e){super(e,"mouse");F(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
{const e=180/Math.PI;self.ea=class extends self.oa{constructor(a){super(a,"audio");this.Ob=this.f=null;this.Qb=this.Tc=!1;this.sa=()=>this.Bg();this.ca=[];this.D=[];this.ha=null;this.Xd="";this.Yd=-1;this.pb=new Map;this.Yc=1;this.qa=!1;this.dd=0;this.bc=1;this.Rc=0;this.$d="HRTF";this.Rd="inverse";this.ae=600;this.Zd=1E4;this.ce=1;this.Td=this.bd=!1;this.fe=this.A.Ke();this.da=new Map;this.Ia=new Set;this.Vc=!1;this.Zc="";this.Ba=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Lf(b,c);this.Nb=null;
self.C3Audio_GetOutputStream=()=>this.Ef();self.C3Audio_DOMInterface=this;H(this,[["create-audio-context",b=>this.gf(b)],["play",b=>this.bg(b)],["stop",b=>this.yg(b)],["stop-all",()=>this.zg()],["set-paused",b=>this.rg(b)],["set-volume",b=>this.wg(b)],["fade-volume",b=>this.mf(b)],["set-master-volume",b=>this.pg(b)],["set-muted",b=>this.qg(b)],["set-silent",b=>this.tg(b)],["set-looping",b=>this.og(b)],["set-playback-rate",b=>this.sg(b)],["seek",b=>this.ig(b)],["preload",b=>this.cg(b)],["unload",b=>
this.Cg(b)],["unload-all",()=>this.Dg()],["set-suspended",b=>this.ug(b)],["add-effect",b=>this.wd(b)],["set-effect-param",b=>this.lg(b)],["remove-effects",b=>this.eg(b)],["tick",b=>this.Xf(b)],["load-state",b=>this.Jf(b)]])}async gf(a){a.isiOSCordova&&(this.bd=!0);this.dd=a.timeScaleMode;this.$d=["equalpower","HRTF","soundfield"][a.panningModel];this.Rd=["linear","inverse","exponential"][a.distanceModel];this.ae=a.refDistance;this.Zd=a.maxDistance;this.ce=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.fe||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.xd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.xd()};this.Ob=this.f.createGain();this.Ob.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.fc();try{await Promise.all(a.preloadList.map(c=>this.Db(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}xd(){this.Qb||(this.Tc=!1,window.addEventListener("pointerup",this.sa,!0),window.addEventListener("touchend",this.sa,!0),window.addEventListener("click",this.sa,!0),window.addEventListener("keydown",this.sa,!0),this.Qb=!0)}jf(){this.Qb&&(this.Tc=!0,window.removeEventListener("pointerup",this.sa,!0),window.removeEventListener("touchend",
this.sa,!0),window.removeEventListener("click",this.sa,!0),window.removeEventListener("keydown",this.sa,!0),this.Qb=!1)}Bg(){if(!this.Tc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.jf()}}W(){return this.f}fc(){return this.f.currentTime}ua(){return this.Ob}nd(a){return(a=this.da.get(a.toLowerCase()))?a[0].P():this.ua()}le(a,b){a=a.toLowerCase();let c=this.da.get(a);
c||(c=[],this.da.set(a,c));b.ng(c.length);b.vg(a);c.push(b);this.Kd(a)}Kd(a){let b=this.ua();const c=this.da.get(a);if(c&&c.length){b=c[0].P();for(let g=0,m=c.length;g<m;++g){const p=c[g];g+1===m?p.S(this.ua()):p.S(c[g+1].P())}}for(const g of this.ma(a))g.Qe(b);this.Ba&&this.Zc===a&&(this.Ba.disconnect(),this.Ba.connect(b))}xb(){return this.Yc}yb(){return this.qa}mg(){this.Td=!0}Ee(a,b){return b?this.A.Eg(a).then(c=>{const g=this.f.createBuffer(1,c.length,48E3);g.getChannelData(0).set(c);return g}):
new Promise((c,g)=>{this.f.decodeAudioData(a,c,g)})}wa(a){this.A.wa(a)}Fa(a){this.A.Fa(a)}sd(a){let b=0;for(let c=0,g=this.D.length;c<g;++c){const m=this.D[c];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Re(){let a=0;for(let b=0,c=this.ca.length;b<c;++b){const g=this.ca[b];this.ca[a]=g;g.va()?g.c():++a}this.ca.length=a}*ma(a){if(a)for(const b of this.D)self.ea.Fe(b.aa,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Db(a,b,c,g,m){for(const p of this.ca)if(p.Ua()===b)return await Y(p),
p;if(m)return null;g&&(this.bd||this.Td)&&this.Re();m="audio/webm; codecs=opus"===c&&!this.fe;g&&m&&this.mg();a=!g||this.bd||m?new self.ze(this,a,b,c,g,m):new self.xe(this,a,b,c,g);this.ca.push(a);await Y(a);return a}async vc(a,b,c,g,m){for(const p of this.D)if(p.Ua()===b&&(p.dc()||m))return p.Te(g),p;a=await this.Db(a,b,c,m);g="html5"===a.Nc?new self.ye(a.i,a,g):new self.Ae(a.i,a,g);this.D.push(g);return g}Xe(a){let b=this.pb.get(a);if(!b){let c=null;b={ed:0,promise:new Promise(g=>c=g),resolve:c};
this.pb.set(a,b)}b.ed++}fg(a){const b=this.pb.get(a);if(!b)throw Error("expected pending tag");b.ed--;0===b.ed&&(b.resolve(),this.pb.delete(a))}rc(a){a||(a=this.Xd);return(a=this.pb.get(a))?a.promise:Promise.resolve()}Eb(){if(0<this.Ia.size)I(this);else for(const a of this.D)if(a.od()){I(this);break}}Ga(){for(var a of this.Ia)a.Ga();a=this.fc();for(var b of this.D)b.Ga(a);b=this.D.filter(c=>c.od()).map(c=>c.Ta());q(this,"state",{tickCount:this.Yd,audioInstances:b,analysers:[...this.Ia].map(c=>c.He())});
0===b.length&&0===this.Ia.size&&this.Rb&&(this.A.gg(this.ge),this.Rb=!1)}nc(a,b,c){q(this,"trigger",{type:a,tag:b,aiid:c})}async bg(a){const b=a.originalUrl,c=a.url,g=a.type,m=a.isMusic,p=a.tag,t=a.isLooping,x=a.vol,z=a.pos,w=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.f.currentTime);this.Xd=p;this.Xe(p);try{this.ha=await this.vc(b,c,g,p,m),w?(this.ha.Ab(!0),this.ha.Se(w.x,
w.y,w.angle,w.innerAngle,w.outerAngle,w.outerGain),w.hasOwnProperty("uid")&&this.ha.Ue(w.uid)):this.ha.Ab(!1),this.ha.Play(t,x,z,y)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.fg(p)}I(this)}yg(a){a=a.tag;for(const b of this.ma(a))b.pa()}zg(){for(const a of this.D)a.pa()}rg(a){const b=a.tag;a=a.paused;for(const c of this.ma(b))a?c.Wa():c.zb();this.Eb()}wg(a){const b=a.tag;a=a.vol;for(const c of this.ma(b))c.Cb(a)}async mf(a){const b=a.tag,c=a.vol,
g=a.duration;a=a.stopOnEnd;await this.rc(b);for(const m of this.ma(b))m.Ge(c,g,a);this.Eb()}pg(a){this.Yc=a.vol;for(const b of this.D)b.Kb()}qg(a){const b=a.tag;a=a.isMuted;for(const c of this.ma(b))c.td(a)}tg(a){this.qa=a.isSilent;this.A.Bb(this.qa);for(const b of this.D)b.Jb()}og(a){const b=a.tag;a=a.isLooping;for(const c of this.ma(b))c.pc(a)}async sg(a){const b=a.tag;a=a.rate;await this.rc(b);for(const c of this.ma(b))c.vd(a)}async ig(a){const b=a.tag;a=a.pos;await this.rc(b);for(const c of this.ma(b))c.oc(a)}async cg(a){const b=
a.originalUrl,c=a.url,g=a.type;a=a.isMusic;try{await this.vc(b,c,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async Cg(a){if(a=await this.Db("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ca.indexOf(a),-1!==a&&this.ca.splice(a,1)}Dg(){for(const a of this.ca)a.c();this.ca.length=0}ug(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.qc(a);a&&this.f.suspend&&this.f.suspend()}Xf(a){this.bc=a.timeScale;this.Rc=a.gameTime;this.Yd=a.tickCount;if(0!==
this.dd)for(var b of this.D)b.Ha();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const g of this.D)g.ga===a&&g.ud(c.x,c.y,c.angle)}}async wd(a){var b=a.type;const c=a.tag;var g=a.params;if("filter"===b)g=new self.re(this,...g);else if("delay"===b)g=new self.pe(this,...g);else if("convolution"===b){b=null;try{b=await this.Db(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}g=new self.oe(this,b.ba,...g);g.jg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.se(this,...g);else if("phaser"===b)g=new self.ue(this,...g);else if("gain"===b)g=new self.te(this,...g);else if("tremolo"===b)g=new self.we(this,...g);else if("ringmod"===b)g=new self.ve(this,...g);else if("distortion"===b)g=new self.qe(this,...g);else if("compressor"===b)g=new self.ne(this,...g);else if("analyser"===b)g=new self.me(this,...g);else throw Error("invalid effect type");this.le(c,
g);this.Jd()}lg(a){const b=a.index,c=a.param,g=a.value,m=a.ramp,p=a.time;a=this.da.get(a.tag);!a||0>b||b>=a.length||(a[b].Y(c,g,m,p),this.Jd())}eg(a){a=a.tag.toLowerCase();const b=this.da.get(a);if(b&&b.length){for(const c of b)c.c();this.da.delete(a);this.Kd(a)}}We(a){this.Ia.add(a);this.Eb()}dg(a){this.Ia.delete(a)}Jd(){this.Vc||(this.Vc=!0,Promise.resolve().then(()=>this.kf()))}kf(){const a={};for(const [b,c]of this.da)a[b]=c.map(g=>g.Ta());q(this,"fxstate",{fxstate:a});this.Vc=!1}async Jf(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.D)c.va()&&1===b||(c.va()||2!==b)&&c.pa();for(const g of this.da.values())for(const m of g)m.c();this.da.clear();this.bc=a.timeScale;this.Rc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.qa=a.isSilent;this.A.Bb(this.qa);this.Yc=a.masterVolume;c=[];for(const g of Object.values(a.effects))c.push(Promise.all(g.map(m=>this.wd(m))));await Promise.all(c);await Promise.all(a.playing.map(g=>this.uf(g,b)));this.Eb()}async uf(a,b){if(3!==
b){var c=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,p=a.isMusic,t=a.tag,x=a.isLooping,z=a.volume,w=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.vc(c,g,m,t,p)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.Oe(a.pan);b.Play(x,z,w,0);a.isPlaying||b.Wa();b.Ac(a)}}}Lf(a,b){this.Ba&&this.Ba.disconnect();this.Zc=b.toLowerCase();this.Ba=this.f.createMediaStreamSource(a);this.Ba.connect(this.nd(this.Zc))}Ef(){this.Nb||(this.Nb=this.f.createMediaStreamDestination(),
this.Ob.connect(this.Nb));return this.Nb.stream}static Fe(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ve(a){return a*e}static De(a){return Math.pow(10,a/20)}static md(a){return Math.max(Math.min(self.ea.De(a),1),0)}static Ne(a){return Math.log(a)/Math.log(10)*20}static Me(a){return self.ea.Ne(Math.max(Math.min(a,1),0))}static Sg(a,b){return 1-Math.exp(-b*a)}};self.X.na(self.ea)}"use strict";function Y(e){e.Tb||(e.Tb=e.zc());return e.Tb}
self.hd=class{constructor(e,a,b,c,g){this.i=e;this.Og=a;this.Da=b;this.R=c;this.Ig=g;this.Nc="";this.Tb=null}c(){this.Tb=this.i=null}zc(){}W(){return this.i.W()}ic(){return this.Og}Ua(){return this.Da}hc(){return this.R}va(){return this.Ig}fa(){}};"use strict";
self.xe=class extends self.hd{constructor(e,a,b,c,g){super(e,a,b,c,g);this.Nc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.jb=this.kb=null;this.J.addEventListener("canplaythrough",()=>!0);this.ob=this.W().createGain();this.mb=null;this.J.addEventListener("canplay",()=>{this.kb&&(this.kb(),this.jb=this.kb=null);!this.mb&&this.J&&(this.mb=this.W().createMediaElementSource(this.J),this.mb.connect(this.ob))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Da}' error: `,m);this.jb&&(this.jb(m),this.jb=this.kb=null)})}c(){this.i.sd(this);this.ob.disconnect();this.ob=null;this.mb.disconnect();this.mb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}zc(){return new Promise((e,a)=>{this.kb=e;this.jb=a;this.J.src=this.Da})}O(){return this.J}fa(){return this.J.duration}};"use strict";
async function da(e){if(e.za)return e.za;var a=e.i.A;if("cordova"===a.u&&a.pd(e.Da)&&"file:"===location.protocol)e.za=await a.vb(e.Da);else{a=await fetch(e.Da);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);e.za=await a.arrayBuffer()}}async function fa(e){if(e.ba)return e.ba;e.ba=await e.i.Ee(e.za,e.Ng);e.za=null}
self.ze=class extends self.hd{constructor(e,a,b,c,g,m){super(e,a,b,c,g);this.Nc="webaudio";this.ba=this.za=null;this.Ng=!!m}c(){this.i.sd(this);this.ba=this.za=null;super.c()}async zc(){try{await da(this),await fa(this)}catch(e){console.error(`[Construct 3] Failed to load audio '${this.Da}': `,e)}}fa(){return this.ba?this.ba.duration:0}};"use strict";
{let e=0;self.jd=class{constructor(a,b,c){this.i=a;this.L=b;this.aa=c;this.Lb=e++;this.M=this.W().createGain();this.M.connect(this.ua());this.B=null;this.hb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.H=!0;this.V=this.la=this.G=!1;this.sb=1;this.Ja=!1;this.$=1;a=this.i.dd;this.Wc=1===a&&!this.va()||2===a;this.eb=this.ga=-1;this.ee=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ua(){return this.i.nd(this.aa)}xb(){return this.i.xb()}wb(){return this.Wc?
this.i.Rc:performance.now()/1E3}ic(){return this.L.ic()}Ua(){return this.L.Ua()}hc(){return this.L.hc()}va(){return this.L.va()}Te(a){this.aa=a}T(){}dc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}od(){return!this.H&&!this.T()}Ea(){}fa(){return this.L.fa()}Play(){}pa(){}Wa(){}zb(){}Cb(a){this.sb=a;this.M.gain.cancelScheduledValues(0);this.eb=-1;this.M.gain.value=this.jc()}Ge(a,b,c){if(!this.Ja){a*=this.xb();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.fc();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.sb=a;this.eb=b;this.ee=c}}Kb(){this.Cb(this.sb)}Ga(a){-1!==this.eb&&a>=this.eb&&(this.eb=-1,this.ee&&this.pa(),this.i.nc("fade-ended",this.aa,this.Lb))}jc(){const a=this.sb*this.xb();return isFinite(a)?a:0}td(a){a=!!a;this.Ja!==a&&(this.Ja=a,this.Jb())}yb(){return this.i.yb()}Jb(){}pc(){}vd(a){this.$!==a&&(this.$=a,this.Ha())}Ha(){}oc(){}qc(){}Ab(a){a=!!a;this.hb!==a&&((this.hb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.$d,this.B.distanceModel=
this.i.Rd,this.B.refDistance=this.i.ae,this.B.maxDistance=this.i.Zd,this.B.rolloffFactor=this.i.ce),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ua())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ua())))}Se(a,b,c,g,m,p){this.hb&&(this.ud(a,b,c),a=self.ea.Ve,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(m),this.B.coneOuterGain=p)}ud(a,b,c){this.hb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(c),this.ja[1]=Math.sin(c),this.ja[2]=0,this.B.setPosition(...this.ka),
this.B.setOrientation(...this.ja))}Ue(a){this.ga=a}kc(){}Qe(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ta(){return{aiid:this.Lb,tag:this.aa,duration:this.fa(),volume:this.sb,isPlaying:this.IsPlaying(),playbackTime:this.Ea(),playbackRate:this.$,uid:this.ga,bufferOriginalUrl:this.ic(),bufferUrl:"",bufferType:this.hc(),isMusic:this.va(),isLooping:this.V,isMuted:this.Ja,resumePosition:this.kc(),pan:this.Ie()}}Ac(a){this.vd(a.playbackRate);this.td(a.isMuted)}Ie(){if(!this.B)return null;const a=
this.B;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Oe(a){if(a){this.Ab(!0);a=this.B;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Ab(!1)}}}"use strict";
self.ye=class extends self.jd{constructor(e,a,b){super(e,a,b);this.L.ob.connect(this.M);this.L.onended=()=>this.Dc()}c(){this.pa();this.L.ob.disconnect();super.c()}O(){return this.L.O()}Dc(){this.H=!0;this.ga=-1;this.i.nc("ended",this.aa,this.Lb)}T(){return this.O().ended}dc(){return this.H?!0:this.T()}Ea(e){let a=this.O().currentTime;e&&(a*=this.$);this.V||(a=Math.min(a,this.fa()));return a}Play(e,a,b){const c=this.O();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==e&&(c.loop=e);this.Cb(a);c.muted&&
(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Ua()}' to position '${b}': `,g)}this.i.wa(c);this.G=this.H=!1;this.V=e;this.$=1}pa(){const e=this.O();e.paused||e.pause();this.i.Fa(e);this.H=!0;this.G=!1;this.ga=-1}Wa(){if(!(this.G||this.H||this.T())){var e=this.O();e.paused||e.pause();this.i.Fa(e);this.G=!0}}zb(){!this.G||this.H||this.T()||(this.i.wa(this.O()),this.G=!1)}Jb(){this.O().muted=this.Ja||this.yb()}pc(e){e=!!e;
this.V!==e&&(this.V=e,this.O().loop=e)}Ha(){let e=this.$;this.Wc&&(e*=this.i.bc);try{this.O().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}oc(e){if(!this.H&&!this.T())try{this.O().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,a)}}kc(){return this.Ea()}qc(e){e?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.wa(this.O()),this.la=!1)}};"use strict";
function Z(e){e.j&&e.j.disconnect();e.j=null;e.$a=null}
self.Ae=class extends self.jd{constructor(e,a,b){super(e,a,b);this.j=null;this.Wb=c=>this.Dc(c);this.Sc=!0;this.$a=null;this.N=this.ac=0;this.$c=1}c(){this.pa();Z(this);this.Wb=null;super.c()}Dc(e){this.G||this.la||e.target!==this.$a||(this.H=this.Sc=!0,this.ga=-1,Z(this),this.i.nc("ended",this.aa,this.Lb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Sc}dc(){return!this.j||this.H?!0:this.T()}Ea(e){let a;a=this.G?this.N:this.wb()-this.ac;e&&(a*=this.$);this.V||(a=Math.min(a,this.fa()));
return a}Play(e,a,b,c){this.$c=1;this.Cb(a);Z(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.ba;this.j.connect(this.M);this.$a=this.j;this.j.onended=this.Wb;this.j.loop=e;this.j.start(c,b);this.G=this.H=this.Sc=!1;this.V=e;this.$=1;this.ac=this.wb()-b}pa(){if(this.j)try{this.j.stop(0)}catch(e){}this.H=!0;this.G=!1;this.ga=-1}Wa(){this.G||this.H||this.T()||(this.N=this.Ea(!0),this.V&&(this.N%=this.fa()),this.G=!0,this.j.stop(0))}zb(){!this.G||this.H||this.T()||(Z(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.L.ba,this.j.connect(this.M),this.$a=this.j,this.j.onended=this.Wb,this.j.loop=this.V,this.Kb(),this.Ha(),this.ac=this.wb()-this.N/(this.$||.001),this.j.start(0,this.N),this.G=!1)}jc(){return super.jc()*this.$c}Jb(){this.$c=this.Ja||this.yb()?0:1;this.Kb()}pc(e){e=!!e;this.V!==e&&(this.V=e,this.j&&(this.j.loop=e))}Ha(){let e=this.$;this.Wc&&(e*=this.i.bc);this.j&&(this.j.playbackRate.value=e)}oc(e){this.H||this.T()||(this.G?this.N=e:(this.Wa(),this.N=e,this.zb()))}kc(){return this.N}qc(e){e?
this.IsPlaying()?(this.la=!0,this.N=this.Ea(!0),this.V&&(this.N%=this.fa()),this.j.stop(0)):this.la=!1:this.la&&(Z(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.ba,this.j.connect(this.M),this.$a=this.j,this.j.onended=this.Wb,this.j.loop=this.V,this.Kb(),this.Ha(),this.ac=this.wb()-this.N/(this.$||.001),this.j.start(0,this.N),this.la=!1)}Ac(e){super.Ac(e);this.N=e.resumePosition}};"use strict";
{class e{constructor(a){this.i=a;this.f=a.W();this.Ud=-1;this.R=this.aa="";this.g=null}c(){this.f=null}ng(a){this.Ud=a}vg(a){this.aa=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,c,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(c){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ta(){return{type:this.R,tag:this.aa,params:this.g}}}
self.re=class extends e{constructor(a,b,c,g,m,p,t){super(a);this.R="filter";this.g=[b,c,g,m,p,t];this.l=this.o();this.b=this.o();this.b.gain.value=t;this.a=this.o();this.a.gain.value=1-t;this.v=this.f.createBiquadFilter();this.v.type=b;this.v.frequency.value=c;this.v.detune.value=g;this.v.Q.value=m;this.v.gain.vlaue=p;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b)}c(){this.l.disconnect();this.v.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 1:this.g[1]=b;this.m(this.v.frequency,b,c,g);break;case 2:this.g[2]=b;this.m(this.v.detune,b,c,g);break;case 3:this.g[3]=b;this.m(this.v.Q,b,c,g);break;case 4:this.g[4]=b,this.m(this.v.gain,b,c,g)}}};self.pe=class extends e{constructor(a,b,c,g){super(a);this.R="delay";this.g=[b,c,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.lb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.cb=this.o();this.cb.gain.value=c;this.l.connect(this.lb);this.l.connect(this.a);this.lb.connect(this.b);this.lb.connect(this.U);this.U.connect(this.cb);this.cb.connect(this.lb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.lb.disconnect();this.U.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){const m=self.ea.md;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 4:this.g[1]=m(b);this.m(this.cb.gain,m(b),c,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,c,g)}}};self.oe=class extends e{constructor(a,b,c,g){super(a);this.R="convolution";this.g=[c,g];this.Pd=this.Od="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.bb=this.f.createConvolver();this.bb.normalize=c;this.bb.buffer=b;this.l.connect(this.bb);this.l.connect(this.a);this.bb.connect(this.b)}c(){this.l.disconnect();this.bb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}jg(a,b){this.Od=a;this.Pd=b}Ta(){const a=
super.Ta();a.bufferOriginalUrl=this.Od;a.bufferUrl="";a.bufferType=this.Pd;return a}};self.se=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="flanger";this.g=[b,c,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.fb=this.o();this.fb.gain.value=m;this.U=this.f.createDelay(b+c);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.I=this.o();this.I.gain.value=c;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.fb);this.fb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.fb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,c,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,g);break;case 8:this.g[3]=b/100,this.m(this.fb.gain,b/100,c,g)}}};self.ue=class extends e{constructor(a,b,c,g,m,p,t){super(a);this.R="phaser";this.g=[b,c,g,m,p,t];this.l=this.o();this.a=this.o();this.a.gain.value=1-t/2;this.b=this.o();this.b.gain.value=t/2;this.v=this.f.createBiquadFilter();this.v.type="allpass";this.v.frequency.value=b;this.v.detune.value=
c;this.v.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=p;this.I=this.o();this.I.gain.value=m;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b);this.s.connect(this.I);this.I.connect(this.v.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.v.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,
b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 1:this.g[0]=b;this.m(this.v.frequency,b,c,g);break;case 2:this.g[1]=b;this.m(this.v.detune,b,c,g);break;case 3:this.g[2]=b;this.m(this.v.Q,b,c,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,c,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,g)}}};self.te=class extends e{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(a,b,c,g){const m=self.ea.md;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),c,g)}}};self.we=class extends e{constructor(a,b,c){super(a);this.R="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=c/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,c,g);this.m(this.I.gain,b/2,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.ve=class extends e{constructor(a,b,c){super(a);this.R="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.rb=this.o();this.rb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.rb.gain);this.s.start(0);this.l.connect(this.rb);this.l.connect(this.a);this.rb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.rb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,c,g);
this.m(this.a.gain,1-b,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.qe=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="distortion";this.g=[b,c,g,m,p];this.l=this.o();this.Yb=this.o();this.Xb=this.o();this.kg(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.cc=this.f.createWaveShaper();this.Pc=new Float32Array(65536);this.pf(b,c);this.cc.curve=this.Pc;this.l.connect(this.Yb);this.l.connect(this.a);this.Yb.connect(this.cc);this.cc.connect(this.Xb);
this.Xb.connect(this.b)}c(){this.l.disconnect();this.Yb.disconnect();this.cc.disconnect();this.Xb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}kg(a,b){.01>a&&(a=.01);this.Yb.gain.value=a;this.Xb.gain.value=Math.pow(1/a,.6)*b}pf(a,b){for(let c=0;32768>c;++c){let g=c/32768;g=this.xg(g,a,b);this.Pc[32768+c]=g;this.Pc[32768-c-1]=-g}}xg(a,b,c){c=1.05*c*b-b;const g=0>a?-a:a;return(g<b?g:b+c*self.ea.Sg(g-b,1/c))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}};self.ne=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="compressor";this.g=[b,c,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(){}};
self.me=class extends e{constructor(a,b,c){super(a);this.R="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Sd=new Float32Array(this.h.frequencyBinCount);this.de=new Uint8Array(b);this.be=this.Ma=0;this.i.We(this)}c(){this.i.dg(this);this.h.disconnect();super.c()}Ga(){this.h.getFloatFrequencyData(this.Sd);this.h.getByteTimeDomainData(this.de);const a=this.h.fftSize;let b=this.Ma=0;for(var c=0;c<a;++c){let g=(this.de[c]-128)/128;0>g&&(g=-g);
this.Ma<g&&(this.Ma=g);b+=g*g}c=self.ea.Me;this.Ma=c(this.Ma);this.be=c(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(){}He(){return{tag:this.aa,index:this.Ud,peak:this.Ma,rms:this.be,binCount:this.h.frequencyBinCount,freqBins:this.Sd}}}};
